### ISSUE TITLE
applying to 2D data

### ISSUE THREAD

**Issue by Red-Portal** [lalonderodney/SegCaps#4]
hi, I tried your model for a 2D dataset but I'm currently struggling.
I basically modified the Load_3D_data.py folder so that the 'generators' emit my data.
However it seems the out_seg_dice_hard is not going up over 0.0369.

Where should I consider to look into in order to use SegCaps for 2D data correctly?
I think the model itself doesn't need much modification, 
assuming the last axis is the for 'channels' in the traditional sense.

**Comment by cclough** [comment]
out_seg_dice_hard is not changing for me either, using my own dataset

what format should the masks be in? one channel per class 8-bit masks? or single band, pixel value = class value?

**Comment by Oushesh** [comment]
Hi Red-Portal,

check this repo: I am also currrently working on Capsules for 2D Image Segmentation.
https://github.com/Cheng-Lin-Li/SegCaps

**Comment by lalonderodney** [comment]
Hello @Red-Portal,

You can checkout @Oushesh, I just looked at his implementation and it looks like he is doing some awesome work! The short answer is to just write your own generator functions that are designed for 2D RGB images rather than 3D CT data which was my purpose. The majority of my research focuses around 3D medical data so I haven't written the 2D RGB equivalents myself.
