### ISSUE TITLE
Reshape anomalies 

### ISSUE THREAD

**Issue by akashkm99** [lalonderodney/SegCaps#6]
https://github.com/lalonderodney/SegCaps/blob/c6b3f9e3e86b6e80652a76408fd6840c1ebe999b/capsule_layers.py#L126-L142

Hey, I feel there is some problem in the way you reshape tensors in the ConvCapsuleLayer class in capsule_layers.py file. 

Shape of input_tensor  --> [None, input_height, input_width, input_num_capsule, input_num_atoms]
Shape of input_transposed --> [input_num_capsule ,None, input_height, input_width, input_num_atoms] Shape of input_tensor_reshaped --> [input_num_capsule *None, input_height, input_width, input_num_atoms]. 

So, input_tensor_reshape[0,...] will contain the 1st capsule of the 1st element in a batch, input_tensor_reshape[1,...] contains the 1st capsule of the 2nd element in a batch and so on. 

Once the convolution operation is finished the conv tensor is reshaped to votes with shape  [None, input_num_capsule, votes_shape[1], votes_shape[2], num_capsule, num_atoms].
 I find a issue here,  when you are reshaping it, shouldn't you make sure it's reshaped to   [input_num_capsule,None, votes_shape[1], votes_shape[2], num_capsule, num_atoms] instead?

**Comment by lalonderodney** [comment]
They are mathematically equivalent since you stick them into the same dimension. Try adding another transpose at the end or instead change the initial reshape to be [batch, input_num_capsules, ...] and you'll see all approaches give the same results. If you wish for consistency to favor the last approach you can. I have actually changed this in my new version (not pushed to here) and the results are identical.
